#!/usr/bin/env python
#-*- coding: utf-8 -*-

import os, sys

def main():
    from optparse import OptionParser
    
    usage = '''
%prog option FILE
use %prog -h to get help'''
    parser = OptionParser(usage)
    parser.add_option("-p", "--parse", dest="pfile", action="store", type="string", help="parse file and print pcode")
    parser.add_option("-i", "--interpreter", dest="ifile", action="store", type="string", help="parse file and interpreter pcode")
    (options, args) = parser.parse_args()
    
    if options.pfile is None and options.ifile is None:
        path = os.path.abspath(sys.path[0]) + os.sep + 'gui'
        os.chdir(path)
        os.execv('/usr/bin/env', ['/usr/bin/env', 'python', 'gui.py'])
    else:
        if options.pfile:
            parse(options.pfile)
        elif options.ifile:
            interpreter(options.ifile)

def parse(pfile):
    from backend.parser import Parser
    p = Parser(pfile)
    if p.error:
        print 'ERROR\N', p.error
        return False
    else:
        print p.get_formated_pcode()
        return p.pcode.pcode

def interpreter(ifile):
    pcode = parse(ifile)
    if pcode:
        from backend.interpreter import Interpreter
        i = Interpreter(pcode)
        i.run()
    
if __name__ == '__main__':
    main()
    
